---
- name: files and perms
  hosts: server2
  become: true
  vars:
    users:
      - name: Annabelle
        group: Sales
      - name: Bob
        group: IT
      - name: Carl
        group: Support
      - name: Dyson
        group: Support
      - name: Evert
        group: IT
      - name: Frank
        group: Sales
      - name: Gerry
        group: Support
      - name: Harold
        group: IT
      - name: Isabella
        group: Services
      - name: Jameson
        group: Services

  tasks: 
#    - name: debug
#      ansible.builtin.shell: "id ctf_sa"
#      register: output
#
#    - name: debug
#      ansible.builtin.debug:
#        msg: "{{  output }}"

#    - name: debug
#      ansible.builtin.find:
#        paths: /
#        pattern: "Salesnumbers"
#      register: output
#
#    - name: debug
#      ansible.builtin.debug:
#        msg: "{{ output }}"

    - name: create files
      ansible.builtin.file: 
        path: "/team/{{ item }}"
        state: directory
        group: "{{ item }}"
        owner: root
        mode: '1777' 
      loop:
        - sales
        - support
        - services
        - it

    - name: create files
      ansible.builtin.file: 
        path: /team/sales/Salesnumbers

    - name: lineinefine
      ansible.builtin.lineinfile: 
        insertbefore: /^(.*)$/m
        path: /it/tasks.done
        line: "all folders are set"
