- name: do storage
  hosts: server2
  become: true
  tasks:
    - name: test parted
      parted:
        device:  /dev/nvme1n1
        number: 2
        state: present
        part_end: 1GB
        fs_type: xfs4
