---
- hosts: all
  gather_facts: false
  tasks:
    - name: install chrony
      ansible.builtin.dnf:
        name: chrony
        state: latest
      become: true

    - name: set primary server
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: '^server 3.north-america.pool.ntp.org'
        line: server 3.north-america.pool.ntp.org