---
- hosts: all
  gather_facts: false
  tasks:
    - name: install chrony
      ansible.builtin.dnf:
        name: 
          - chrony
          - cockpit
        state: latest
      become: true

    - name: enable cockput
      ansible.builtin.shell:
        cmd: |
          systemctl enable --now cockpit.socket
      become: true

    - name: create dir 
      ansible.builtin.file:
        path: /etc/chrony
        state: directory
        mode: '0755'
      become: true

    - name: set primary server
      ansible.builtin.copy:
        dest: /etc/chrony/chrony.conf
        content: 'server 3.north-america.pool.ntp.org'
      become: true

    - name: Ensure a job 
      ansible.builtin.cron:
        name: "cockpit"
        minute: "0"
        hour: "5,2"
        job: "systemctl is-active cockpit.service >> /var/log/automation.log"
      become: true