---
- name:  create users
  hosts: all
  become: true
  vars:
    user_pass: '@#FD12'
  tasks: 
    - name: create users
      ansible.builtin.user: 
        name: "{{ item }}"
        password: "{{ user_pass }}"
      loop:
        - Annabelle
        - Bob
        - Carl
        - Dyson
        - Evert
        - Frank
        - Gerry
        - Harold
        - Isabella
        - Jameson
        

