---
- name:  create users
  hosts: all
  vars:
     pass: @#FD12
  tasks: 
    - name: create users
      ansible.builtin.user: 
        name: "{{ item }}"
        password: "{{ pass }}"
      loop:
        - Annabelle
        - Bob
        - Carl
        - Dyson
        - Evert
        - Frank
        - Gerry
        - Harold
        - Isabella
        - Jameson
        

